on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: lint

jobs:
  lint:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, local::.

      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}